import React,{useEffect,useMemo,useState} from 'react';
import { Eye,Search,UserRound } from 'lucide-react';
import { Aluno,Matricula } from '../types';
import { apiService,getStoredAlunos,getStoredMatriculas } from '../services/api';
import { limpaCPF } from '../utils/cpfUtils';
import { FichaAluno } from './FichaAluno';

interface Props { onEditarAluno?:(a:Aluno)=>void; onAdicionarMatricula?:(a:Aluno)=>void; onExcluirAluno?:(a:Aluno)=>void|Promise<void>; onEditarMatricula?:(a:Aluno,m:Matricula)=>void; onExcluirMatricula?:(m:Matricula)=>void|Promise<void> }
export const ConsultaAlunos:React.FC<Props>=({onEditarAluno,onAdicionarMatricula,onExcluirAluno,onEditarMatricula,onExcluirMatricula})=>{
 const [alunos,setAlunos]=useState<Aluno[]>([]),[matriculas,setMatriculas]=useState<Matricula[]>([]),[busca,setBusca]=useState(''),[selecionado,setSelecionado]=useState<Aluno|null>(null),[carregando,setCarregando]=useState(true);
 useEffect(()=>{apiService.sincronizarComPlanilha(true).finally(()=>{setAlunos(getStoredAlunos());setMatriculas(getStoredMatriculas());setCarregando(false)})},[]);
 const resultados=useMemo(()=>{const q=busca.trim().toLocaleLowerCase('pt-BR'),cpf=limpaCPF(busca);if(!q)return alunos.slice(0,30);return alunos.filter(a=>a.nomeCompleto.toLocaleLowerCase('pt-BR').includes(q)||(cpf&&limpaCPF(a.cpf).includes(cpf))).slice(0,50)},[alunos,busca]);
 return <section className="max-w-6xl mx-auto py-6"><div className="bg-white border rounded-3xl shadow-sm overflow-hidden"><div className="bg-sky-700 text-white p-6"><h2 className="text-2xl font-black">Consulta de alunos</h2><p className="text-sky-100 text-sm mt-1">Pesquise pelo nome ou CPF e abra a ficha completa.</p></div><div className="p-5"><label className="flex items-center gap-3 border-2 rounded-2xl px-4"><Search className="text-slate-400"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Digite o nome ou CPF" className="w-full py-4 outline-none" autoFocus/></label><div className="mt-5 grid md:grid-cols-2 gap-3">{carregando?<div className="text-sm text-slate-500">Sincronizando alunos...</div>:resultados.map(a=><button key={a.idAluno} onClick={()=>setSelecionado(a)} className="text-left border rounded-2xl p-4 hover:border-sky-400 hover:bg-sky-50 flex items-center gap-4"><div className="w-12 h-12 rounded-xl bg-slate-100 overflow-hidden flex items-center justify-center">{a.fotoUrl?<img src={a.fotoUrl} alt="" className="w-full h-full object-cover"/>:<UserRound className="text-slate-300"/>}</div><div className="min-w-0 flex-1"><b className="block truncate">{a.nomeCompleto}</b><span className="text-xs text-slate-500">{a.cpf} • {matriculas.filter(m=>m.idAluno===a.idAluno).length} matrícula(s)</span></div><Eye className="w-5 h-5 text-sky-600"/></button>)}</div>{!carregando&&resultados.length===0&&<div className="text-center py-10 text-slate-500">Nenhum aluno encontrado.</div>}</div></div>{selecionado&&<FichaAluno aluno={selecionado} matriculas={matriculas.filter(m=>m.idAluno===selecionado.idAluno)} onFechar={()=>setSelecionado(null)} onEditar={()=>onEditarAluno?.(selecionado)} onMatricular={()=>onAdicionarMatricula?.(selecionado)} onExcluir={async()=>{await onExcluirAluno?.(selecionado);setSelecionado(null);setAlunos(getStoredAlunos());setMatriculas(getStoredMatriculas())}} onEditarMatricula={m=>onEditarMatricula?.(selecionado,m)} onExcluirMatricula={async m=>{await onExcluirMatricula?.(m);setMatriculas(getStoredMatriculas())}}/>}</section>;
};
