import React, { useState } from 'react';
import { Check, Copy, FileText, MapPin, Pencil, Printer, Save, Trash2, UserPlus, UserRound, X } from 'lucide-react';
import { Aluno, Matricula } from '../types';
import { gerarPDFMatricula } from '../services/pdfGenerator';

interface Props { aluno:Aluno; matriculas:Matricula[]; onFechar:()=>void; onEditar?:()=>void; onExcluir?:()=>void|Promise<void>; onMatricular?:()=>void; onEditarMatricula?:(m:Matricula)=>void; onExcluirMatricula?:(m:Matricula)=>void|Promise<void>; onSalvarAluno?:(aluno:Aluno)=>Promise<Aluno|void> }

export const FichaAluno:React.FC<Props> = ({aluno,matriculas,onFechar,onEditar,onExcluir,onMatricular,onEditarMatricula,onExcluirMatricula,onSalvarAluno}) => {
  const [gerando,setGerando]=useState('');
  const [telefoneCopiado,setTelefoneCopiado]=useState('');
  const [situacao,setSituacao]=useState<NonNullable<Aluno['situacao']>>(aluno.situacao || 'Ativo');
  const [observacoes,setObservacoes]=useState(aluno.observacoes || '');
  const [salvandoFicha,setSalvandoFicha]=useState(false);
  const [salvoFicha,setSalvoFicha]=useState(false);
  const [erroFicha,setErroFicha]=useState('');
  const abrirPdf=async(m:Matricula,imprimir=false)=>{setGerando(m.idMatricula);try{const bytes=await gerarPDFMatricula(aluno,m);const url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/pdf'}));const janela=window.open(url,'_blank');if(imprimir&&janela)janela.addEventListener('load',()=>janela.print(),{once:true});window.setTimeout(()=>URL.revokeObjectURL(url),60000);}finally{setGerando('')}};
  const copiarTelefone=async(rotulo:string,telefone:string)=>{try{await navigator.clipboard.writeText(telefone);}catch{const campo=document.createElement('textarea');campo.value=telefone;campo.style.position='fixed';campo.style.opacity='0';document.body.appendChild(campo);campo.select();document.execCommand('copy');campo.remove();}setTelefoneCopiado(rotulo);window.setTimeout(()=>setTelefoneCopiado(''),1800);};
  const salvarFicha=async()=>{if(!onSalvarAluno)return;setSalvandoFicha(true);setSalvoFicha(false);setErroFicha('');try{await onSalvarAluno({...aluno,situacao,observacoes:observacoes.trim()});setSalvoFicha(true);window.setTimeout(()=>setSalvoFicha(false),1800);}catch(erro){setErroFicha(erro instanceof Error?erro.message:'Não foi possível salvar a ficha.');}finally{setSalvandoFicha(false)}};
  const campos=[{rotulo:'Telefone do aluno',valor:aluno.telefoneAluno,copiavel:true},{rotulo:'Telefone da mãe',valor:aluno.telefoneMae,copiavel:true},{rotulo:'Telefone do pai',valor:aluno.telefonePai,copiavel:true},{rotulo:'Nascimento',valor:aluno.dataNascimento},{rotulo:'CPF',valor:aluno.cpf},{rotulo:'RG',valor:aluno.rg},{rotulo:'Naturalidade',valor:aluno.naturalidade},{rotulo:'Gênero',valor:aluno.genero},{rotulo:'Escola',valor:aluno.escolaEstuda},{rotulo:'Série',valor:aluno.serie},{rotulo:'Responsável',valor:aluno.responsavel}];
  return <div className="fixed inset-0 bg-slate-950/60 z-50 p-3 md:p-8 overflow-y-auto">{telefoneCopiado&&<div className="fixed inset-0 z-[70] pointer-events-none flex items-center justify-center"><div className="flex items-center gap-2 rounded-full bg-slate-950/90 text-white px-5 py-3 shadow-2xl text-sm font-bold animate-in fade-in zoom-in"><Check className="w-4 h-4 text-emerald-400"/>Telefone copiado</div></div>}<article className="max-w-5xl mx-auto bg-white rounded-3xl shadow-2xl overflow-hidden">
    <header className="bg-indigo-950 text-white p-5 flex justify-between items-start"><div><p className="text-xs uppercase tracking-widest text-indigo-300">Ficha do aluno</p><h2 className="text-2xl font-black mt-1">{aluno.nomeCompleto}</h2><p className="text-sm text-indigo-200">ID {aluno.idAluno}</p></div><button onClick={onFechar} className="p-2 rounded-xl bg-white/10"><X/></button></header>
    <div className="p-5 md:p-8 space-y-8"><div className="flex flex-wrap gap-2"><button onClick={onEditar} disabled={!onEditar} className="px-4 py-2 rounded-xl bg-sky-50 text-sky-800 font-bold flex gap-2 disabled:hidden"><Pencil className="w-4 h-4"/>Editar aluno</button><button onClick={onMatricular} disabled={!onMatricular} className="px-4 py-2 rounded-xl bg-emerald-50 text-emerald-800 font-bold flex gap-2 disabled:hidden"><UserPlus className="w-4 h-4"/>Matricular</button><button onClick={onExcluir} disabled={!onExcluir} className="px-4 py-2 rounded-xl bg-rose-50 text-rose-700 font-bold flex gap-2 disabled:hidden"><Trash2 className="w-4 h-4"/>Excluir aluno</button></div>
    <div className="grid md:grid-cols-[180px_1fr] gap-6"><div className="aspect-[3/4] rounded-2xl bg-slate-100 border overflow-hidden flex items-center justify-center">{aluno.fotoUrl?<img src={aluno.fotoUrl} alt={aluno.nomeCompleto} className="w-full h-full object-cover"/>:<UserRound className="w-16 h-16 text-slate-300"/>}</div><div><h3 className="font-extrabold mb-3">Dados pessoais</h3><div className="grid sm:grid-cols-2 gap-3">{campos.map(campo=><div key={campo.rotulo} className="rounded-xl bg-slate-50 border p-3"><div className="text-[10px] uppercase font-bold text-slate-400">{campo.rotulo}</div><div className="flex items-center justify-between gap-2 mt-1"><div className="text-sm font-semibold">{campo.valor||'Não informado'}</div>{campo.copiavel&&campo.valor&&<button type="button" onClick={()=>void copiarTelefone(campo.rotulo,campo.valor||'')} className="p-1.5 rounded-lg text-indigo-700 hover:bg-indigo-100 shrink-0" title={`Copiar ${campo.rotulo.toLowerCase()}`} aria-label={`Copiar ${campo.rotulo.toLowerCase()}`}>{telefoneCopiado===campo.rotulo?<Check className="w-4 h-4 text-emerald-600"/>:<Copy className="w-4 h-4"/>}</button>}</div></div>)}</div><div className="mt-3"><div className="flex gap-2 rounded-xl bg-slate-50 border p-3"><MapPin className="w-4 h-4 text-indigo-600 shrink-0"/><span className="text-sm">{[aluno.enderecoRua,aluno.numero,aluno.bairro,aluno.cidade].filter(Boolean).join(', ')||'Endereço não informado'}</span></div></div></div></div>
    <section className="rounded-2xl border bg-slate-50 p-5"><div className="flex flex-wrap items-end gap-4"><label className="min-w-48"><span className="block text-xs font-extrabold text-slate-600 mb-2">Situação do aluno</span><select value={situacao} onChange={e=>setSituacao(e.target.value as NonNullable<Aluno['situacao']>)} disabled={!onSalvarAluno} className="w-full border bg-white rounded-xl px-3 py-3 text-sm font-bold"><option>Ativo</option><option>Inativo</option><option>Cancelado</option></select></label><label className="flex-1 min-w-64"><span className="block text-xs font-extrabold text-slate-600 mb-2">Observações</span><textarea value={observacoes} onChange={e=>setObservacoes(e.target.value)} disabled={!onSalvarAluno} rows={3} placeholder="Registre aqui informações importantes sobre o aluno" className="w-full border bg-white rounded-xl px-3 py-3 text-sm resize-y"/></label><button type="button" onClick={()=>void salvarFicha()} disabled={!onSalvarAluno||salvandoFicha} className="px-5 py-3 rounded-xl bg-indigo-600 text-white font-bold flex items-center gap-2 disabled:opacity-50"><Save className="w-4 h-4"/>{salvandoFicha?'Salvando...':salvoFicha?'Salvo':'Salvar situação e observações'}</button></div>{erroFicha&&<p className="mt-3 text-sm font-bold text-rose-700">{erroFicha}</p>}</section>
    <section><h3 className="font-extrabold mb-3">Matrículas ({matriculas.length})</h3><div className="space-y-3">{matriculas.length===0?<div className="border border-dashed rounded-2xl p-6 text-sm text-slate-500">Nenhuma matrícula vinculada.</div>:matriculas.map(m=><div key={m.idMatricula} className="border rounded-2xl p-4 flex flex-wrap justify-between gap-4 items-center"><div><b>{m.turma||`${m.curso} - ${m.horario}`}</b><div className="text-xs text-slate-500 mt-1">{m.anoSemestre} • {m.idMatricula}</div></div><div className="flex flex-wrap gap-2"><button disabled={!!gerando} onClick={()=>abrirPdf(m)} className="px-3 py-2 text-xs font-bold rounded-lg bg-indigo-50 text-indigo-700 flex gap-1"><FileText className="w-4 h-4"/>Visualizar PDF</button><button disabled={!!gerando} onClick={()=>abrirPdf(m,true)} className="px-3 py-2 text-xs font-bold rounded-lg bg-slate-100 text-slate-700 flex gap-1"><Printer className="w-4 h-4"/>Imprimir</button><button onClick={()=>onEditarMatricula?.(m)} disabled={!onEditarMatricula} className="px-3 py-2 text-xs font-bold rounded-lg bg-sky-50 text-sky-700 flex gap-1 disabled:hidden"><Pencil className="w-4 h-4"/>Editar</button><button onClick={()=>onExcluirMatricula?.(m)} disabled={!onExcluirMatricula} className="px-3 py-2 text-xs font-bold rounded-lg bg-rose-50 text-rose-700 flex gap-1 disabled:hidden"><Trash2 className="w-4 h-4"/>Excluir</button></div></div>)}</div></section></div>
  </article></div>;
};
