import React, { useEffect, useMemo, useState } from 'react';
import { Eye, Plus, Save, Search, Trash2, UserMinus, UserPlus, UsersRound, X } from 'lucide-react';
import { Aluno, Matricula, Turma } from '../types';
import { SessaoUsuario } from '../services/auth';
import { apiService, getStoredAlunos, getStoredMatriculas } from '../services/api';
import { listarTurmas, removerTurma, salvarTurma } from '../services/turmas';
import { FichaAluno } from './FichaAluno';
import { CONFIG } from '../config';

export const TurmasPage: React.FC<{ sessao: SessaoUsuario }> = ({ sessao }) => {
  const [turmas,setTurmas]=useState<Turma[]>([]),[alunos,setAlunos]=useState<Aluno[]>([]),[matriculas,setMatriculas]=useState<Matricula[]>([]),[selecionada,setSelecionada]=useState<Turma|null>(null),[ficha,setFicha]=useState<Aluno|null>(null),[busca,setBusca]=useState(''),[criando,setCriando]=useState(false),[compartilhadas,setCompartilhadas]=useState(false);
  const [nova,setNova]=useState({nome:'',curso:'Teatro' as Turma['curso'],horario:'Manhã' as Turma['horario'],nivel:'' as Turma['nivel']});
  const recarregar=async()=>{const r=await listarTurmas();setTurmas(r.turmas);setCompartilhadas(r.compartilhadas);setSelecionada(s=>s?r.turmas.find(t=>t.idTurma===s.idTurma)||null:null);};
  useEffect(()=>{Promise.all([apiService.sincronizarComPlanilha(true),recarregar()]).finally(()=>{setAlunos(getStoredAlunos());setMatriculas(getStoredMatriculas());});},[]);
  const membros=selecionada?alunos.filter(a=>selecionada.alunosIds.includes(a.idAluno)):[];
  const candidatos=useMemo(()=>{if(!selecionada)return[];const ids=new Set(matriculas.filter(m=>m.curso===selecionada.curso&&m.horario===selecionada.horario&&m.anoSemestre===selecionada.anoSemestre).map(m=>m.idAluno));const q=busca.toLocaleLowerCase('pt-BR');return alunos.filter(a=>ids.has(a.idAluno)&&!selecionada.alunosIds.includes(a.idAluno)&&(!q||a.nomeCompleto.toLocaleLowerCase('pt-BR').includes(q)||a.cpf.includes(busca))).slice(0,50);},[selecionada,alunos,matriculas,busca]);
  const atualizar=async(t:Turma)=>{await salvarTurma(t);await recarregar();setSelecionada(t);};
  const criar=async(e:React.FormEvent)=>{e.preventDefault();if(!nova.nome.trim())return;const r=await salvarTurma({idTurma:'',nome:nova.nome.trim(),curso:nova.curso,horario:nova.horario,nivel:nova.nivel,anoSemestre:CONFIG.ANO_SEMESTRE_DEFAULT,alunosIds:[],criadaPor:sessao.nome,ativa:true});setCriando(false);setNova({nome:'',curso:'Teatro',horario:'Manhã',nivel:''});await recarregar();setSelecionada(r.turma);};
  return <section className="max-w-7xl mx-auto py-6 space-y-5"><div className="flex flex-wrap justify-between gap-4 items-end"><div><div className="flex items-center gap-2 text-violet-700 font-bold"><UsersRound/>Gestão de turmas</div><h2 className="text-3xl font-black mt-1">Turmas da Escola de Artes</h2><p className="text-sm text-slate-500 mt-1">{compartilhadas?'Sincronizadas com a planilha.':'Modo preview: alterações salvas neste navegador até o novo Apps Script ser implantado.'}</p></div><button onClick={()=>setCriando(true)} className="px-5 py-3 bg-violet-600 text-white rounded-xl font-bold flex gap-2"><Plus/>Criar nova turma</button></div>
  <div className="grid lg:grid-cols-[360px_1fr] gap-5"><aside className="bg-white border rounded-3xl p-4 h-fit"><div className="space-y-2">{turmas.map(t=><button key={t.idTurma} onClick={()=>{setSelecionada(t);setBusca('')}} className={`w-full text-left p-4 rounded-2xl border transition ${selecionada?.idTurma===t.idTurma?'bg-violet-50 border-violet-400':'hover:bg-slate-50'}`}><div className="flex justify-between gap-2"><b>{t.nome}</b><span className="text-xs rounded-full bg-slate-100 px-2 py-1 h-fit">{t.alunosIds.length}</span></div><div className="text-xs text-slate-500 mt-1">{t.anoSemestre} • {t.curso} / {t.horario}</div></button>)}</div></aside>
  <main className="bg-white border rounded-3xl min-h-[520px]">{!selecionada?<div className="h-full flex flex-col items-center justify-center text-center p-10 text-slate-500"><UsersRound className="w-14 h-14 text-slate-300 mb-3"/><b>Selecione uma turma</b><span className="text-sm">Veja os alunos ou monte a composição da turma.</span></div>:<><header className="p-5 border-b flex flex-wrap justify-between gap-3"><div><h3 className="text-xl font-black">{selecionada.nome}</h3><p className="text-xs text-slate-500 mt-1">Filtro de matrícula: {selecionada.curso} - {selecionada.horario}</p></div>{!selecionada.preCriada&&<button onClick={async()=>{if(confirm('Excluir esta turma?')){await removerTurma(selecionada.idTurma);setSelecionada(null);await recarregar();}}} className="text-rose-600 p-2"><Trash2/></button>}</header><div className="p-5 grid xl:grid-cols-2 gap-6"><div><h4 className="font-bold mb-3">Alunos da turma ({membros.length})</h4><div className="space-y-2">{membros.length===0?<div className="border border-dashed rounded-xl p-5 text-sm text-slate-500">Nenhum aluno adicionado.</div>:membros.map(a=><div key={a.idAluno} className="border rounded-xl p-3 flex items-center gap-2"><div className="flex-1 min-w-0"><b className="text-sm block truncate">{a.nomeCompleto}</b><span className="text-xs text-slate-500">{a.cpf}</span></div><button onClick={()=>setFicha(a)} title="Exibir ficha" className="p-2 text-sky-600"><Eye className="w-4 h-4"/></button><button onClick={()=>atualizar({...selecionada,alunosIds:selecionada.alunosIds.filter(id=>id!==a.idAluno)})} title="Remover da turma" className="p-2 text-rose-600"><UserMinus className="w-4 h-4"/></button></div>)}</div></div><div><h4 className="font-bold mb-3">Adicionar matriculados</h4><label className="flex border rounded-xl px-3 items-center gap-2"><Search className="w-4 h-4 text-slate-400"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Nome ou CPF" className="w-full py-3 outline-none text-sm"/></label><div className="mt-3 space-y-2 max-h-96 overflow-y-auto">{candidatos.map(a=><div key={a.idAluno} className="border rounded-xl p-3 flex items-center gap-2"><div className="flex-1 min-w-0"><b className="text-sm block truncate">{a.nomeCompleto}</b><span className="text-xs text-slate-500">{a.cpf}</span></div><button onClick={()=>atualizar({...selecionada,alunosIds:[...selecionada.alunosIds,a.idAluno]})} className="p-2 text-emerald-600"><UserPlus className="w-4 h-4"/></button></div>)}{candidatos.length===0&&<div className="text-sm text-slate-500 p-4">Nenhum matriculado disponível para este filtro.</div>}</div></div></div></>}</main></div>
  {criando&&<div className="fixed inset-0 bg-slate-950/60 z-40 p-4 flex items-center justify-center"><form onSubmit={criar} className="bg-white rounded-3xl w-full max-w-lg p-6 space-y-4"><div className="flex justify-between"><h3 className="text-xl font-black">Criar nova turma</h3><button type="button" onClick={()=>setCriando(false)}><X/></button></div><input required value={nova.nome} onChange={e=>setNova({...nova,nome:e.target.value})} placeholder="Nome da turma" className="w-full border rounded-xl px-4 py-3"/><div className="grid grid-cols-2 gap-3"><select value={nova.curso} onChange={e=>setNova({...nova,curso:e.target.value as Turma['curso']})} className="border rounded-xl px-3 py-3"><option>Teatro</option><option>Música</option></select><select value={nova.horario} onChange={e=>setNova({...nova,horario:e.target.value as Turma['horario']})} className="border rounded-xl px-3 py-3"><option>Manhã</option><option>Tarde</option><option>Noite</option><option>Núcleo</option></select></div><select value={nova.nivel} onChange={e=>setNova({...nova,nivel:e.target.value as Turma['nivel']})} className="w-full border rounded-xl px-3 py-3"><option value="">Sem nível</option><option>Sementes</option><option>Aperfeiçoamento</option></select><button className="w-full bg-violet-600 text-white py-3 rounded-xl font-bold flex justify-center gap-2"><Save/>Salvar turma</button></form></div>}
  {ficha&&<FichaAluno aluno={ficha} matriculas={matriculas.filter(m=>m.idAluno===ficha.idAluno)} onFechar={()=>setFicha(null)}/>}</section>;
};
