import React,{useEffect,useMemo,useState} from 'react';
import { Eye,Plus,Save,Search,Trash2,UserMinus,UserPlus,UsersRound,X } from 'lucide-react';
import { Aluno,Matricula,Turma } from '../types';
import { SessaoUsuario } from '../services/auth';
import { apiService,getStoredAlunos,getStoredMatriculas } from '../services/api';
import { listarTurmas,removerTurma,salvarTurma } from '../services/turmas';
import { FichaAluno } from './FichaAluno';
import { CONFIG } from '../config';

interface Props{sessao:SessaoUsuario;onEditarAluno?:(a:Aluno)=>void;onAdicionarMatricula?:(a:Aluno)=>void;onExcluirAluno?:(a:Aluno)=>void|Promise<void>;onEditarMatricula?:(a:Aluno,m:Matricula)=>void;onExcluirMatricula?:(m:Matricula)=>void|Promise<void>}
const FotoMiniatura=({aluno}:{aluno:Aluno})=><div className="w-11 h-11 rounded-full bg-slate-100 border overflow-hidden shrink-0 flex items-center justify-center text-xs font-black text-slate-400">{aluno.fotoUrl?<img src={aluno.fotoUrl} alt="" className="w-full h-full object-cover"/>:aluno.nomeCompleto.slice(0,1)}</div>;
export const TurmasPage:React.FC<Props>=({sessao,onEditarAluno,onAdicionarMatricula,onExcluirAluno,onEditarMatricula,onExcluirMatricula})=>{
 const [turmas,setTurmas]=useState<Turma[]>([]),[alunos,setAlunos]=useState<Aluno[]>([]),[matriculas,setMatriculas]=useState<Matricula[]>([]),[selecionada,setSelecionada]=useState<Turma|null>(null),[ficha,setFicha]=useState<Aluno|null>(null),[busca,setBusca]=useState(''),[criando,setCriando]=useState(false),[compartilhadas,setCompartilhadas]=useState(false),[sincronizando,setSincronizando]=useState(false);
 const [nova,setNova]=useState({nome:'',curso:'Teatro' as Turma['curso'],horario:'Manhã' as Turma['horario'],nivel:'' as Turma['nivel']});
 const recarregar=async()=>{const r=await listarTurmas();setTurmas(r.turmas);setCompartilhadas(r.compartilhadas);setSelecionada(s=>s?r.turmas.find(t=>t.idTurma===s.idTurma)||null:null)};
 useEffect(()=>{Promise.all([apiService.sincronizarComPlanilha(true),recarregar()]).finally(()=>{setAlunos(getStoredAlunos());setMatriculas(getStoredMatriculas())})},[]);
 const membros=selecionada?alunos.filter(a=>selecionada.alunosIds.includes(a.idAluno)):[];
 const candidatos=useMemo(()=>{if(!selecionada)return[];const ids=new Set(matriculas.filter(m=>m.curso===selecionada.curso&&m.horario===selecionada.horario&&m.anoSemestre===selecionada.anoSemestre).map(m=>m.idAluno));const q=busca.toLocaleLowerCase('pt-BR');return alunos.filter(a=>ids.has(a.idAluno)&&!selecionada.alunosIds.includes(a.idAluno)&&(!q||a.nomeCompleto.toLocaleLowerCase('pt-BR').includes(q)||a.cpf.includes(busca)))},[selecionada,alunos,matriculas,busca]);
 const atualizar=(t:Turma)=>{setSelecionada(t);setTurmas(lista=>lista.map(item=>item.idTurma===t.idTurma?t:item));setSincronizando(true);void salvarTurma(t).then(r=>setCompartilhadas(r.compartilhada)).finally(()=>setSincronizando(false))};
 const criar=async(e:React.FormEvent)=>{e.preventDefault();if(!nova.nome.trim())return;const r=await salvarTurma({idTurma:'',nome:nova.nome.trim(),curso:nova.curso,horario:nova.horario,nivel:nova.nivel,anoSemestre:CONFIG.ANO_SEMESTRE_DEFAULT,alunosIds:[],criadaPor:sessao.nome,ativa:true});setCriando(false);await recarregar();setSelecionada(r.turma)};
 const adicionarTodos=()=>{if(!selecionada||!candidatos.length)return;atualizar({...selecionada,alunosIds:[...new Set([...selecionada.alunosIds,...candidatos.map(a=>a.idAluno)])]})};
 return <section className="max-w-7xl mx-auto py-6 space-y-5"><div className="flex flex-wrap justify-between gap-4 items-end"><div><div className="flex items-center gap-2 text-violet-700 font-bold"><UsersRound/>Gestão de turmas</div><h2 className="text-3xl font-black mt-1">Turmas da Escola de Artes</h2><p className="text-sm text-slate-500 mt-1">{sincronizando?'Salvo no banco. Enfileirando backup…':compartilhadas?'Dados carregados do D1; backup da planilha em segundo plano.':'Banco temporariamente indisponível.'}</p></div><button onClick={()=>setCriando(true)} className="px-5 py-3 bg-violet-600 text-white rounded-xl font-bold flex gap-2"><Plus/>Criar nova turma</button></div>
 <div className="grid lg:grid-cols-[360px_1fr] gap-5"><aside className="bg-white border rounded-3xl p-4 h-fit"><div className="space-y-2">{turmas.map(t=><button key={t.idTurma} onClick={()=>{setSelecionada(t);setBusca('')}} className={`w-full text-left p-4 rounded-2xl border ${selecionada?.idTurma===t.idTurma?'bg-violet-50 border-violet-400':'hover:bg-slate-50'}`}><div className="flex justify-between gap-2"><b>{t.nome}</b><span className="text-xs bg-slate-100 px-2 py-1 rounded-full">{t.alunosIds.length}</span></div><div className="text-xs text-slate-500 mt-1">{t.anoSemestre} • {t.curso} / {t.horario}</div></button>)}</div></aside>
 <main className="bg-white border rounded-3xl min-h-[520px]">{!selecionada?<div className="h-full flex flex-col items-center justify-center p-10 text-slate-500"><UsersRound className="w-14 h-14 text-slate-300"/><b>Selecione uma turma</b></div>:<><header className="p-5 border-b flex justify-between"><div><h3 className="text-xl font-black">{selecionada.nome}</h3><p className="text-xs text-slate-500">Filtro: {selecionada.curso} - {selecionada.horario}</p></div>{!selecionada.preCriada&&<button onClick={async()=>{if(confirm('Excluir esta turma?')){await removerTurma(selecionada.idTurma);setSelecionada(null);await recarregar()}}} className="text-rose-600"><Trash2/></button>}</header>
 <div className="p-5 grid xl:grid-cols-2 gap-6"><div><h4 className="font-bold mb-3">Alunos da turma ({membros.length})</h4><div className="space-y-2">{membros.length===0?<div className="border border-dashed rounded-xl p-5 text-sm text-slate-500">Nenhum aluno adicionado.</div>:membros.map(a=><div key={a.idAluno} className="border rounded-xl p-3 flex items-center gap-3"><FotoMiniatura aluno={a}/><div className="flex-1 min-w-0"><b className="text-sm block truncate">{a.nomeCompleto}</b><span className="text-xs text-slate-500">{a.cpf}</span></div><button onClick={()=>setFicha(a)} title="Exibir ficha" className="p-2 text-sky-600"><Eye className="w-4 h-4"/></button><button onClick={()=>atualizar({...selecionada,alunosIds:selecionada.alunosIds.filter(id=>id!==a.idAluno)})} title="Remover" className="p-2 text-rose-600"><UserMinus className="w-4 h-4"/></button></div>)}</div></div>
 <div><div className="flex items-center justify-between gap-3 mb-3"><h4 className="font-bold">Adicionar matriculados</h4><button onClick={adicionarTodos} disabled={!candidatos.length} className="px-3 py-2 rounded-xl bg-emerald-600 text-white text-xs font-bold flex gap-1 disabled:opacity-40"><UserPlus className="w-4 h-4"/>Adicionar todos ({candidatos.length})</button></div><label className="flex border rounded-xl px-3 items-center gap-2"><Search className="w-4 h-4 text-slate-400"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Nome ou CPF" className="w-full py-3 outline-none text-sm"/></label><div className="mt-3 space-y-2 max-h-96 overflow-y-auto">{candidatos.map(a=><div key={a.idAluno} className="border rounded-xl p-3 flex items-center gap-3"><FotoMiniatura aluno={a}/><div className="flex-1 min-w-0"><b className="text-sm block truncate">{a.nomeCompleto}</b><span className="text-xs text-slate-500">{a.cpf}</span></div><button onClick={()=>setFicha(a)} title="Visualizar ficha" aria-label={`Visualizar ficha de ${a.nomeCompleto}`} className="p-2 rounded-lg text-sky-600 hover:bg-sky-50"><Eye className="w-4 h-4"/></button><button onClick={()=>atualizar({...selecionada,alunosIds:[...selecionada.alunosIds,a.idAluno]})} title="Adicionar à turma" className="p-2 rounded-lg text-emerald-600 hover:bg-emerald-50"><UserPlus className="w-4 h-4"/></button></div>)}{!candidatos.length&&<div className="text-sm text-slate-500 p-4">Nenhum matriculado disponível.</div>}</div></div></div></>}</main></div>
 {criando&&<div className="fixed inset-0 bg-slate-950/60 z-40 p-4 flex items-center justify-center"><form onSubmit={criar} className="bg-white rounded-3xl w-full max-w-lg p-6 space-y-4"><div className="flex justify-between"><h3 className="text-xl font-black">Criar nova turma</h3><button type="button" onClick={()=>setCriando(false)}><X/></button></div><input required value={nova.nome} onChange={e=>setNova({...nova,nome:e.target.value})} placeholder="Nome da turma" className="w-full border rounded-xl px-4 py-3"/><div className="grid grid-cols-2 gap-3"><select value={nova.curso} onChange={e=>setNova({...nova,curso:e.target.value as Turma['curso']})} className="border rounded-xl px-3 py-3"><option>Teatro</option><option>Música</option></select><select value={nova.horario} onChange={e=>setNova({...nova,horario:e.target.value as Turma['horario']})} className="border rounded-xl px-3 py-3"><option>Manhã</option><option>Tarde</option><option>Noite</option><option>Núcleo</option></select></div><button className="w-full bg-violet-600 text-white py-3 rounded-xl font-bold flex justify-center gap-2"><Save/>Salvar turma</button></form></div>}
 {ficha&&<FichaAluno aluno={ficha} matriculas={matriculas.filter(m=>m.idAluno===ficha.idAluno)} onFechar={()=>setFicha(null)} onAlunoAtualizado={atualizado=>{setFicha(atualizado);setAlunos(lista=>lista.map(item=>item.idAluno===atualizado.idAluno?atualizado:item))}} onEditar={()=>onEditarAluno?.(ficha)} onMatricular={()=>onAdicionarMatricula?.(ficha)} onExcluir={async()=>{await onExcluirAluno?.(ficha);setFicha(null);setAlunos(getStoredAlunos());setMatriculas(getStoredMatriculas())}} onEditarMatricula={m=>onEditarMatricula?.(ficha,m)} onExcluirMatricula={async m=>{await onExcluirMatricula?.(m);setMatriculas(getStoredMatriculas())}}/>}</section>;
};
